tcp_server:
	clear
	g++ tcp_server.cpp -o tcp_server.exe
	./tcp_server.exe
tcp_client:
	clear
	g++ tcp_client.cpp -o tcp_client.exe
	./tcp_client.exe
udp_server:
	clear	
	g++ udp_server.cpp -o udp_server.exe
	./udp_server.exe
udp_client:
	clear
	g++ udp_client.cpp -o udp_client.exe
	./udp_client.exe
clean:
	rm -f *.exe
